[package]
name = "snap_0_2_4"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
lazy_static = "0.1"
snap = "0.2.4"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
